### ISSUE TITLE
Bildhafte Anzeige der verbleibenden Wiegezeit

### ISSUE THREAD

**Issue by Regattawaage** [frank71336/Mrv.Regatta.Waage#2]
Eine bildhafte Anzeige, z.B. ein Balkendiagramm, welches auf einen Blick die verbleibende Wiegezeit für ein Rennen darstellt.
Z.B. könnte vor Beginn des Zeitfensters der Balken komplett orange sein (hier auf einheitliche Farbgebung für Signalzustände achten). Bei Eintritt in das Wiegezeitfenster 2h vor dem Rennen wird der Balken komplett grün. Bis 1h vor dem Rennen wird der Balken immer kürzer (restliche Farbe mit der aufgefüllt wird hellgrau von oben beginnend).
Bei Ablauf der Wiegezeit ist der Balken grau. 

Da Kinderrennen keinen festgelegten frühesten Wiegezeitpunkt haben, sollte die Anzeige vor dem Rennen immer grün sein und wie bei den anderen Rennen 2h vor Rennbeginn anfangen "abzulaufen".

R/G/B:
grau: 200/200/200
grün: 0/200/0 oder passend zu vorhandenen Farben
orange: 255/180/0 oder passend zu vorhandenen Farben

**Comment by frank71336** [comment]
Erledigt. RGB-Vorgaben bei Implementierung ignoriert.
