### ISSUE TITLE
Anzeige bei überschrittenem Gewicht

### ISSUE THREAD

**Issue by Regattawaage** [frank71336/Mrv.Regatta.Waage#5]
Bisher erschien bei überschrittenem Gewicht ein grüner Haken zur Anzeige des abgeschlossenen Wiegevorgangs was zu Verwirrungen führte.
Statt des grünen Hakens sollte ein rotes Kreuz oder etwas vergleichbares zum Einsatz kommen welches optisch eindeutig darstellt, dass zwar ein Wiegevorgang stattfand, der Teilnehmer jedoch nicht innerhalb der Gewichtsgrenze lag.
Hierbei muss auch das Manschaftsdurchschnittsgewicht geprüft und entsprechend markiert werden.

**Comment by frank71336** [comment]
Das ist nicht ganz einfach, was, wenn er in zwei Rennen gemeldet ist, und das Gewicht für das eine Rennen OK, für das andere aber nicht? Oder aber, wenn er zu spät ist für das kommende Rennen, aber noch rechtzeitig für das übernächste?

**Comment by Regattawaage** [comment]
Der Status des Ruderers müsste für jedes Rennen gesondert mit den Renn-spezifischen Zeiten und Gewichten abgeglichen und dargestellt werden.
